name: CI
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
jobs:
  build-container:
    needs: test
    name: "Build container image"
    uses: curium-rocks/flows/.github/workflows/oci-build-image.yml@main
    with:
      image_name: website
      push_in_pr: true